"""empty message

Revision ID: 1151ad4d5775
Revises: 
Create Date: 2022-03-06 21:26:17.212617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1151ad4d5775'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customerSQL') as op_ba :
        op_ba.create_unique_constraint("usr_make_name", ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customerSQL', type_='unique')
    # ### end Alembic commands ###
